# sudo docker exec -it <c_id> mongosh -u root -p 1111

version: '3.1'

services:
  mongo:
    image: mongo
    cpus: 0.2
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1111

volumes:
  mongo-db:
