#sudo docker exec -it <id_c> psql -U postgres -d postgres
#sudo docker exec -it <id_c> su - postgres -c psql

version: '3.9'

services:
  postgres:
    image: postgres
    cpus: 0.2
    restart: always
    shm_size: 128mb
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1111

volumes:
  postgres-db:
